name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC-5
    - cron: '0 5 * * 1'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ▁▂▃▅▆▇
